### ISSUE TITLE
problem with free-bound calculation

### ISSUE THREAD

**Issue by kdere** [chianti-atomic/ChiantiPy#137]
the final free-bound calculation comes together inside a try: statement so it is not obvious what is happening.  Looking at it a bit it comes from trying to multiply 2 or 3 arrays together that have the wrong dimensions for this operation.  One of the arrays seems to the the EM but that is not always the sticking point.

**Comment by wtbarnes** [comment]
What file and line number are being referenced specifically? is this in the `Continuum` module or `spectrum` module?

**Comment by kdere** [comment]
I just ran the code again, just as the user supplied, and got no errors.  I may have done a pull from my origin master in between the two runs.  

The problem had been in the Spectrum module after line 170

**Comment by kdere** [comment]
I just checked and I was using the v0.7.0 release so th bug may still be there in Spectrum after line 170

**Comment by kdere** [comment]
went back to the trunk version (~0.7.1) and the problem still seemed to be gone

**Comment by wtbarnes** [comment]
When you say v0.7.1, do you mean the master branch at the most current commit?

**Comment by kdere** [comment]
yes, that is what I meant, I was speaking in svn

**Comment by wtbarnes** [comment]
I ran the code snippet from the mailing list on the most current commit  of master and it didn't error, but I didn't think that was the issue. I thought the problem was that the free-bound contribution to spectrum gives zero over that particular wavelength range and that this result is not correct.

**Comment by kdere** [comment]
yes, your are right.  I just forgot

**Comment by wtbarnes** [comment]
Just to consolidate the issue to this thread, the code to calculate the spectrum in ChiantiPy is,

```Python
temp=[1.e+7,2.e+7]
dens=1.e+9
wvl = 1. + 0.002*np.arange(4501)
emeas=[1.e+27,1.e+27]
s3 = ch.spectrum(temperature=temp,eDensity=dens,wavelength=wvl,filter = (chfilters.gaussian,.015),doContinuum=1, em=emeas,minAbund=1.e-5,verbose=0)
plt.plot(wvl,s3.FreeFree['intensity'][0])
plt.plot(wvl,s3.FreeBound['intensity'][0])
```
![image](https://user-images.githubusercontent.com/8676141/27306266-99bf3830-550a-11e7-94ae-61dc48cd19bd.png)

while the corresponding IDL output gives,
![image](https://user-images.githubusercontent.com/8676141/27306472-54adf348-550b-11e7-97d7-e50dc334d9e8.png)

(solid is free-free, dashed is free-bound, dot-dashed is two-photon)

The next step I guess would just be to make sure that the `Continuum` module alone is giving the expected output, e.g. something like 

```Python
mport numpy as np
import ChiantiPy.core as ch
import ChiantiPy.tools.data as chdata

temperature = np.array([1e7,2e7])
wavelength = np.linspace(1,10,4501)
total_fb_emission = np.zeros((temperature.shape[0],wavelength.shape[0]))

for ion in chdata.MasterList:
    tmp = ch.Continuum(ion,temperature)
    tmp.calculate_free_bound_emission(wavelength)
    total_fb_emission += tmp.free_bound_emission
```

If it does, then we know the problem is confined to `spectrum`

**Comment by kdere** [comment]
the problem is in Continuum, at line 449, in inserted

```
        if self.emission_measure is not None:
            for i, em in enumerate(self.emission_measure):
                fb_emiss[i] *= em

```
for this problem, fb has a shape of [2,4501] and emeas has a shape of [2] and they can not be directly multiplied together.  I have put a correction and have pushed to to my fork and then will do it to the upstream master

also, line 421:  requires an array of temperatures, not a float - it tries to get len(temperature)
I will let you work on this because the code with regard to this has changed from what I had
in v

**Comment by wtbarnes** [comment]
Ok yes that's a problem. There are a couple of other corner cases I've hit where things cannot be multiplied together because of weird dimension mismatches. Note that this can be solved with `numpy.newaxis`. See my comment in #139. As they come up, I'll try to fix them. I think most of the time it is just a matter of using the `numpy.newaxis` fix. This is probably a case where more tests with a larger range of inputs would be useful...

Regarding line 421, I don't think this is an issue because of [this line](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Continuum.py#L59) in the constructor which makes sure temperature is a Numpy array so calling `len()` on it shouldn't be a problem.

**Comment by kdere** [comment]
there is another problem with the fix and that is when emission_measure is not interable.
never used numpy.newaxis
I think I should leave this to you

**Comment by kdere** [comment]
the free-bound calculation now works with a single temperature.  However, the syntax has mostly reverted to the original style

`import numpy as np
import ChiantiPy.core as ch
import ChiantiPy.tools.data as chdata

temperature = np.array([1e7,2e7])
wavelength = np.linspace(1,10,4501)
total_fb_emission = np.zeros((temperature.shape[0],wavelength.shape[0]))

for ion in chdata.MasterList:
    tmp = ch.continuum(ion,temperature)
    tmp.freeBound(wavelength)
    total_fb_emission += tmp.FreeBound['intensity']`

previously, freeBound would through an error if the data file necessary to do the calculation was missing.  Now it just returns a correctly shaped array of zeros.
