### ISSUE TITLE
relabelling chianti to Chiantipy and changes in the directory structure.

### ISSUE THREAD

**Issue by kdere** [chianti-atomic/ChiantiPy#14]
this got messed up.  chiantipy is a fairly tightly integrated packed so that moving all the directories around can cause a big mess.

**Comment by wtbarnes** [comment]
Where specifically is this a problem? It seems that moving a set routines, say to `ChiantiPy/tools`, should not have any impact provided a package's import statement, e.g. `import chianti.constants as const`, is changed appropriately to `import ChiantiPy.tools.constants as const`. Thus, all references to functions, variables, etc., in `const` are still valid.

The reasoning behind the module rename was because the bootstrapping in the Astropy package template complains when the package name (ChiantiPy) and the module name (then chianti) are not the same.

**Comment by kdere** [comment]
Yes, you are right.  Sorry for the delay for getting back to you but I had some health problems.

**Comment by wtbarnes** [comment]
No problem at all. Hope things are going well.

There were a few places where I had not fixed the import statements to account for the `tools` directory and the package rename, but those should all be fixed now by #13 which has just been merged (Thanks!). They were being caught by Read the Docs (since it does a full install of the package when it builds the documentation). It is passing now so I think this issue can be closed.
