### ISSUE TITLE
RTD does not build

### ISSUE THREAD

**Issue by kdere** [chianti-atomic/ChiantiPy#192]
The first time it failed recently, it gave the message:

ImportError: No module named 'PyQt4'
when it was import conda stuff
the next error message was
KeyError: 'XUVTOP', again in the middle of working with conda

this has happened a number of times and then more recently, the build failed with

The error message starts off with:

Fetching package metadata .............
Solving package specifications: .
ca-certificate   0% |                              | ETA:  --:--:--   0.00  B/s
ca-certificate  11% |###                            | ETA:  0:00:00   2.76 MB/s
ca-certificate  22% |#######                        | ETA:  0:00:00   4.83 MB/s
ca-certificate  34% |##########                     | ETA:  0:00:00   6.89 MB/s
ca-certificate  45% |##############                 | ETA:  0:00:00   8.74 MB/s
ca-certificate  56% |#################              | ETA:  0:00:00  10.34 MB/s
ca-certificate  68% |#####################          | ETA:  0:00:00  10.71 MB/s
ca-certificate  79% |########################       | ETA:  0:00:00  11.95 MB/s
ca-certificate  91% |############################   | ETA:  0:00:00  12.57 MB/s
ca-certificate 100% |###############################| ETA:  0:00:00  13.34 MB/s
ca-certificate 100% |###############################| Time: 0:00:00  13.10 MB/s

and ends with

matplotlib-2.0   0% |                              | ETA:  --:--:--   0.00  B/s

matplotlib-2.0  94% |#############################  | Time: 0:00:00  38.02 MB/s
matplotlib-2.0  94% |#############################  ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::attrs-17.4.0-py_0'.
OSError(12, 'Cannot allocate memory')
Attempting to roll back.

OSError(12, 'Cannot allocate memory')

**Comment by wtbarnes** [comment]
As far as the most recent build is concerned, I have no idea what is going on. I've never seen this error on RTD before. I suspect this is an RTD issue and you *should* be able to just restart the build. 

Regarding the build prior to that one, there are two things going on:
1. The import of the GUI module fails because it PyQt4 is not installed, [this line specifically](https://github.com/chianti-atomic/ChiantiPy/blob/6681be96f2496313885899e38de398b5f8795b87/ChiantiPy/Gui/gui_qt/gui.py#L5). Even though we've pinned PyQt to v4, it looks like RTD is updating it to v5 for some reason. You can see this in the [second step of the install step](https://readthedocs.org/projects/chiantipy/builds/6806612/) when it installs sphinx. Why were we pinning to PyQt4 again? It seems like there was a good reason, but I cannot remember why. Does the GUI module work with PyQt5? If it does, you could add a try-except block to use 4 or 5, something like
```python
try:
    from PyQt4 import QtGui
except ImportError:
    from PyQt5 import QtGui
```

2. The `KeyError` regarding the `XUVTOP` variable is expected as we don't install the database on RTD since it takes too long. The exception is handled [here](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/tools/data.py#L37) so it should not actually interrupt the build process but it will print a warning to STDOUT. 

So I think once the PyQt4/5 issue is handled, the docs should build fine.

**Comment by ktritz** [comment]
I've modified/added files to get ChiantiPy to run with PyQt5. I can issue a pull request if people are interested. It's not just changing the import as PyQt5 changes the inheritance of a many widgets and deprecates some of the code used.

**Comment by kdere** [comment]
I have noticed that things have changed in the PyQt world.  This seems to include the way that Matplotlib works.  
Can you be a bit more specific.  For example will the current PyQt4 widgets still work or do we need PyQt5 widgets?
I am very interested.

**Comment by ktritz** [comment]
The main change in the code is that many widgets were moved from QtGui to QtWidgets. They also changed the way you connect functions to events. Other than these changes, the rest of the code seems to work the same as far as I've seen so far. Basically I just duplicated the qui_qt directory and modified the code to work with PyQt5. Then put a check in the main __init__.py to load PyQt5 if it is available.

**Comment by kdere** [comment]
I think the way it should work is to first check for a the availability of PyQt5 and then use that widget set, then if PyQt5 is not available, use the PyQt4 widget set if that is available.  
This would require a set of PyQt5 widgets that have the same names and functionality as the PyQt4.  Also, the CLI interface should be available as a last resort.
Hopefully, you are thinking along these lines.
I can fix the multiple selection for PyQt4 unless you have already done this.

**Comment by kdere** [comment]
go ahead an issue a pull request and then I can see what things will look like

**Comment by ktritz** [comment]
I have not fixed the multiple selection for PyQt4.

There are at least three different ways to handle the PyQt4 vs. PyQt5. The easiest, which is what I did, was just copy the PyQt4 code and make the changes to the inheritance as needed. However, this means you have two places to make changes to the widgets in the future.

Another way is to have a qt4/qt5 flag, and use 'from --- import ---' based on the flag, like:
if pyqt5_flag:
  from QtWidgets import QListBox, QDialog, ...
else:
  from QtGui import QListBox, QDialog, ...

and then in the code you just use QListBox as you like

if you don't like using 'from' inheritance, you can use something like:

if pyqt5_flag:
  import QtWidgets as QImport
else:
  import QtGui as QImport

and then in the code, use QImport.QListBox, and so on.

The last two examples can share the overall widget codebase between PyQt4 and 5.

**Comment by kdere** [comment]
It has been years since those widgets were written so I do not expect too many changed until PyQt6 comes along or something that major.  I would keep the PyQt4 module as it and add a PyQt5 module.

I would rather not have a flag as that would be a **Default** value and I don't think most users are used to changing what is initially shipped.

Currently, we do a try/except to see what gui packages are available.  We could do this for PyQt5, PyQt4 and then the CLI.  I think it is time to drop wxPython as it is only Python2 compliant

**Comment by ktritz** [comment]
I agree. As my code is set up now, it should automatically check for PyQt5, then PyQt4, and load the appropriate GUI module.

**Comment by kdere** [comment]
As far as I can see, it looks good.  will wait for the build to finish

**Comment by kdere** [comment]
as of version 0.14.0 and most previous version, the docs do build on RTD
