### ISSUE TITLE
No older versions in PyPI

### ISSUE THREAD

**Issue by epassaro** [chianti-atomic/ChiantiPy#244]
Hi,

There are only two versions available in PyPI right now ( 0.7.1a0 and 0.8.5). Here we're using 0.8.4 and would like to stick to that one, but seems not possible right now.

Also we have problems with 0.8.5 that I described in #243

Thanks.

**Comment by kdere** [comment]
yes, 0.8.5 has some problems and 0.7.1a0 is out of date with respect to the v9 CHIANTI database.
I will hope to get the 0.8.6 update out soon, mostly with fixes for the ion module
thanks for letting me know.
Ken

**Comment by wkerzendorf** [comment]
In general it would be nice to have all versions available - I presume you are deleting them from pypi manually.

**Comment by kdere** [comment]
Yes, I am deleting them manually.  Will try to keep them all in the future unless they no longer are appropriate for the latest CHIANTI dataset.

Ken

On 6/17/19 2:07 PM, Wolfgang Kerzendorf wrote:

In general it would be nice to have all versions available - I presume you are deleting them from pypi manually.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1ZkDraAXueoHohGuv1cYxgxuzQXoq5N3oJcEz02M1zdKfsZZn02CQO1i0qmOKMKjfGLDGAIv0AtITse0XfgnoBZw-1S5RXkSUMTewmLdTig6jbc3X_m_ZX_58GDS3NiNVuGLx2Opa2YAfWOMjt6beqkBUKoalcKDf-LFdeMOQzVpYoFHeBEI2NJHIwKqUC4qIIuPO22rk4fD4Cgl62jBXFRqHkVDjeRXG7MXsLuSoVvxPnyo0M2ZMRlu-wbh2zClpyajgT0ic-qPAbXbF2qApgtxMB2kYRlnbaMSmKHJZUhuEbtLVZJX6muk7BtzqKkAms1eJTmsr1tysAsQEPkU5S2zUhyId4EdwVlEmHR_RN56DPSjcG4deodrzBvvOjbGl/https%3A%2F%2Fgithub.com%2Fchianti-atomic%2FChiantiPy%2Fissues%2F244%3Femail_source%3Dnotifications%26email_token%3DAAFUQVQ4SXB2V5GAH7WY3HTP27HH3A5CNFSM4HYYWQN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX37Y5I%23issuecomment-502791285>, or mute the thread<https://secure-web.cisco.com/1VhUoj2Sj4li5QKe9EskKLzsVH9yGsGP__4CcU7kVtxiTr8wOopm2EzM10sqaVZtPrH0G7vZcEsO863q_8wg!
PDRfOvU7wwBpLGuQZpp3Sz2aOAVPHvhWsfpTY_iDZUE2r2cdp8jMc5AS61DZs8C59GZPSEt18b0zIqEHuYlwZoZ4R3xeEZKDlcIF9aOhhDErKKYGStjrucr_pdRCy3dulp0aob_qiAMe1jpS4V1U99LM5NpE5TLC8B2IPVmLPlhbBmdl6S8_2rYZQgGLIJHWZiT9a-JWWaP-So7s9GKbzI2oO6m3Ku5ZR8-EGdCN_F17RU3_B2myFtNUKstQ2Y0E6bp1PwOmy0tU_MznFLNhHUKLiR2jOReF3NszbqKGIhok4/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAFUQVXLNA5IT356SSPCOSDP27HH3ANCNFSM4HYYWQNQ>.

--
Kenneth P. Dere
Research Professor of Solar Physics
Department of Physics and Astronomy
George Mason University
kdere@gmu.edu<mailto:kdere@gmu.edu>

**Comment by wkerzendorf** [comment]
I guess you still have all CHIANTI versions online, right? I think it would be great to have CHIANTIPy say for what version of chianti it is useful. BTW thanks for doing the effort of making this fantastic easily accessible!

**Comment by kdere** [comment]
somehow I managed to restore a number of older ChiantiPy version to PyPI.  They were hiding under dist and I uploaded dist/*

yes, it would be good to know what ChiantiPy versions went with which CHIANTI version.  I will try to pay attention to that in the future
