### ISSUE TITLE
Ni II Energy Level Order

### ISSUE THREAD

**Issue by trmillertr** [chianti-atomic/ChiantiPy#256]
Hello ChiantiPy Developers,
The .elvlc file for Ni II lists the first four energy levels as 0, 8393.9, 1506.94, and 9330.04 where the first excited level (1506.94) is listed after the second excited level (8393.9). Is this order correct? For example, if I want to calculate the population levels for the 1506.94 level, is it 

nion = ch.ion('ni_2',temperature=10000,eDensity=3000)
nion.populate()
nion.Population['population'][2]

or

nion.Population['population'][1]

Calculating over a grid of densities and comparing ratios w.r.t. ground leads me to believe that the order is not correct and should be 0, 1506.94, 8393.9, 9330.04. Please see the attached figure. In general, should the energy levels in every .elvlc file be from smallest to largest energies? It is the case for the majority that I have looked at with exceptions including Ni II.

Thank you for your help. 

![Ni_IIPopulationRatios](https://user-images.githubusercontent.com/49995847/66497806-0bc00c80-ea8b-11e9-8c32-510c758ca8e4.png)

**Comment by kdere** [comment]
The Ni II energies come from Version 3 of the NIST database and were inserted into CHIANTI in 2009.  The current version of NIST has the levels in order of their energy.  However, the model in CHIANTI still has them sorted as you list:  0, 1506.94, 8393.9, 9330.04.  So, the population of the level with E=1506 is listed in the energy level files as level 2 which corresponds to an index of 1:  nion.Population['population'][1].
Hope this helps.
Ken

**Comment by trmillertr** [comment]
Ok. Just to be clear, the listing in the .elvlc which has 8393.9 first and then 1506.94 is wrong and the model CHIANTI uses has them sorted from lowest to highest energies. Is that true for all models for every other species? What would be the way to see what energy level is associated with the nion.Population['population'][i] for index i?
Thanks again,
Tim
________________________________

**Comment by kdere** [comment]
In general, but not always, the levels are  sorted by energy, from lowest to highest.  In the case of Ni II, they are not sorted by energy.  The energy levels are shown in the /ni/ni_2/ni_2.elvlc file in the CHIANTI database or in the on-line version [](https://www.chiantidatabase.org/sswidl/dbase/ni/ni_2/ni_2.elvlc)

**Comment by kdere** [comment]
the online version:
https://www.chiantidatabase.org/sswidl/dbase/ni/ni_2/ni_2.elvlc
can be reach from chiantidatabase.org by following the link to direct access

**Comment by trmillertr** [comment]
This is the file I was referring to in the original post. If I read that file,
nion.Elvlc['ecm'][0:5] = 0, 8393.9, 1506.94, 9330.04, 10115.66
and from what you stated before
nion.Population['population'][x=1] corresponds to the 1506.94 energy level, it doesn't match the indexing of that file (1506.94 is index 2). The 8393.9 and 1506.94 levels are switched. How can I check to see what energy level is associated with index x of nion.Population['population'][x]?
________________________________

**Comment by kdere** [comment]
nion.Elvlc['pretty'][x] will give you the level description

**Comment by trmillertr** [comment]
Ok, but it is getting that information from the ni_2.elvlc file of which for the 8393.9 and 1506.94 energy levels are out of order. Is there an alternate way to check what energy level is associated with the nion.Population['population'][x], or is it assumed that the indexing is x=0=lowest energy level, i.e. 0 cm^-1, x=1=next highest energy level, i.e. 1506.94 cm^-1, etc. even though the order in the ni_2.elvlc file is not from smallest to largest?
________________________________

**Comment by kdere** [comment]
yes, it just goes by the indexing, 0 for the ground level and on up, 1 for the next level and so on

**Comment by pryoung** [comment]
Hi Tim,

I put the Ni II model into CHIANTI so I'll comment about the indexing. Typically when I do a CHIANTI model I'll take the level ordering from the theoretical model that gives the electron excitation data. In this case it's the Bautista (2004) paper. He assigned the 3d^9 levels to indices 1 and 3, and 4s 4F9/2 as index 2. As you've noted, the NIST energy ordering is different. The index ordering does not make any difference to the calculation of level populations. So even if the 3d^9 levels were given indices 1 and 10, and the 4F9/2 level was given index 7, then the results will still be the same. 

Now, Ni II is somewhat unusual in that the 4F9/2 gains population more quickly than 3d9 2D3/2 as density increases. Typically levels gain population in the order determined by their energies, so you would expect 2D3/2 to gain population first. The reason is that the 4F9/2 level has a much smaller radiative decay rate to the ground than 2D3/2, *and* there is no decay rate from 4F9/2 to 2D3/2. The unusual hump in the 4F9/2 population I believe is due to level 4 (4F7/2). At low densities there are excitations from level 1 to level 4, which then decays to level 2. As 4F7/2 gains population then the direct electron de-excitation  from level 4 to level 2 becomes dominant but is actually less efficient (in terms of transitions per second) and so the level 2 population drops relative to the other levels. 

Hope this makes sense,  Peter.

**Comment by trmillertr** [comment]
Hi Peter,

If that's the case then the order listed in the ni_2.elvlc for the energy levels is the same order that nion.Population['population'] has, with 8393.9 indexed 1 and 1506.94 indexed 2. Correct? This is the opposite of what Ken originally said so I want to make sure I am understanding which energy level is associated with each population.

Thank you,
Tim
________________________________

**Comment by pryoung** [comment]
Yes, I believe so. I work with the IDL version of CHIANTI and that's how the indexing works there. I don't think ChiantiPy would be different.

**Comment by kdere** [comment]
In that respect, ChiantiPy works the same as the IDL package.
